FROM mysql:latest

# Adicionando os scripts SQL para serem executados na criação do banco
COPY ./Scripts/CriacaoBD/ /docker-entrypoint-initdb.d/

CMD [ "--default-authentication-plugin=mysql_native_password" ]


